
[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[general]
live_config_reload = true

[font]
size = 14.0

[font.normal]
style = "Regular"

[window]
dynamic_padding = false

[window.padding]
x = 8
y = 6

[keyboard]
